"""esquema inicial: users, sources, entries, contexts

Revision ID: c502a77d28b2
Revises: 
Create Date: 2026-09-09 12:45:04.671108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c502a77d28b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('user_id', 'checksum', name=op.f('uq_sources_user_id'))
    )
    op.create_index(op.f('ix_sources_user_id'), 'sources', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.Column('lemma', sa.String(length=120), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_entries_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries')),
    sa.UniqueConstraint('user_id', 'lemma', 'lang', name=op.f('uq_entries_user_id'))
    )
    op.create_index(op.f('ix_entries_lang'), 'entries', ['lang'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('contexts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_sentence', sa.Text(), nullable=False),
    sa.Column('clean_sentence', sa.Text(), nullable=True),
    sa.Column('is_truncated', sa.Boolean(), nullable=False),
    sa.Column('book_title', sa.String(length=500), nullable=True),
    sa.Column('book_lang', sa.String(length=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_contexts_entry_id_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contexts')),
    sa.UniqueConstraint('entry_id', 'external_id', name=op.f('uq_contexts_entry_id'))
    )
    op.create_index(op.f('ix_contexts_entry_id'), 'contexts', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contexts_entry_id'), table_name='contexts')
    op.drop_table('contexts')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_lang'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_sources_user_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('users')
    # ### end Alembic commands ###
